### ISSUE TITLE
内存泄露的问题

### ISSUE THREAD

**Issue by zhouwude** [li6185377/IMYWebView#11]
[config.userContentController addScriptMessageHandler:self name:@"xxx"];可能会对self强引用造成内存泄露，在removeScriptMessageHandlerForName之后可以解决这个问题但是删除之后再次添加 就调不起js了有什么 好的解决办法没有。

**Comment by li6185377** [comment]
可以在 VC Dealloc 里面 再去remove

**Comment by zhouwude** [comment]
感谢您的回复，主要是这个timer类似 对self强引用后压根就走不到dealloc里面。

**Comment by li6185377** [comment]
可以用 类似 Weak Proxy 包一层
