### ISSUE TITLE
为什么要把NJKWebViewProgress 集成进去？

### ISSUE THREAD

**Issue by Whirlwind** [li6185377/IMYWebView#13]
我看项目中copy了NJKWebViewProgress 的部分代码，为什么不直接用Pod 引用？

要是copy了，把NJKWebViewProgressView 也copy一份啊！现在我手动加入 NJKWebViewProgress 的库，还出现 completeRPCURL 变量符号冲突。

**Comment by Whirlwind** [comment]
使用 `pod 'NJKWebViewProgress/ProgressView` 解决变量符号冲突

**Comment by li6185377** [comment]
这个是 Xcode8 造成的。 可以看这篇文章 http://www.cocoachina.com/ios/20160919/17589.html 
不过我代码也改造下

**Comment by li6185377** [comment]
已修改，Xcode8 编译可过
