### ISSUE TITLE
关于redme 中的警告，可能找到了原因

### ISSUE THREAD

**Issue by dadadong** [li6185377/IMYWebView#14]
-(void)setScalesPageToFit:(BOOL)scalesPageToFit
把上面个方法中的 那段js代码删掉 就好了 ，因为淘宝的页面 已经包含了viewport mate标签，并且 witdh= 0.333   ， 你那段js改成了witdh= 1.   。。。  所以 放大了

**Comment by li6185377** [comment]
> 已改 可以看下最新分支的代码。 目前我看了下 淘宝 已经修复了相关bug，代码不更新 显示也是正常的
