### ISSUE TITLE
无法调用js方法

### ISSUE THREAD

**Issue by Sunxb** [li6185377/IMYWebView#15]
JSContext * context = [(UIWebView *)webView.realWebView valueForKeyPath:@"documentView.webView.mainFrame.javaScriptContext"];
    NSString * alertJS = @"alert('test js OC')"; //准备执行的js代码
    [context evaluateScript:alertJS];

崩在第一句

**Comment by li6185377** [comment]
页面没加载 或者 WKWebView  都没法提供 JSContext。  IMYWebView 头文件已经有暴露 JSContext
