### ISSUE TITLE
拿到jscontext的方式无法统一

### ISSUE THREAD

**Issue by lxzhh** [li6185377/IMYWebView#2]
UIWebView可以从
`valueForKeyPath:@"documentView.webView.mainFrame.javaScriptContext"`
拿到jscontext，但WKWebView要从
`- (void)userContentController:(WKUserContentController *)userContentController didReceiveScriptMessage:(WKScriptMessage *)message;`
回调里面拿到js的信息，完全是两种不同的用法，有办法统一吗

**Comment by li6185377** [comment]
那只能内部再自己封装一层了

**Comment by li6185377** [comment]
目前WK没法直接取到JSContext， 只能在外部增加了两个API  
![image](https://cloud.githubusercontent.com/assets/1924211/15667181/5ad83776-2747-11e6-888f-5809317281c1.png)
