### ISSUE TITLE
项目中使用了IMYWebView后,审核失败

### ISSUE THREAD

**Issue by CodeXYu** [li6185377/IMYWebView#20]
IMYWebView中使用那些系统热更新关键字了吗?  现在审核不过了

**Comment by li6185377** [comment]
苹果有说用到了什么 私有API 吗？内部邮件的内容是什么？

**Comment by CodeXYu** [comment]
与远程资源相结合的代码与App Store最初审核时相比，可以促进对应用程序行为的重大更改。虽然您目前可能没有使用此功能，但它有可能加载私有框架，私有方法，并启用将来的功能更改。这包括将任意参数传递给动态方法的任何代码，例如dlopen（），dlsym（），respondToSelector :, performSelector :, method_exchangeImplementations（），并运行远程脚本，以便更改应用程序行为和/或调用SPI，基于内容下载的脚本。即使远程资源没有有意的恶意，也可以轻易地通过中间人（MiTM）攻击劫持，这可能会给您的应用程序的用户造成严重的安全漏洞。

**Comment by li6185377** [comment]
这个应该是你用 JSPatch 吧

**Comment by CodeXYu** [comment]
没有..上周更新是没问题的,这周只添加了这个三方库.然后就不行了

**Comment by li6185377** [comment]
内部没有用私有API，上周开始混淆过的 JSPatch 也审核不过了，你看下是不是有其他库引用了

**Comment by CodeXYu** [comment]
好吧.我再研究研究

**Comment by stdawn** [comment]
那现在可以用吗， 影不影响上线？

**Comment by CodeXYu** [comment]
没问题了。。我发现它把之前未审核的百度统计也算进去了，老版本的百度统计里面可能有jspatch

**Comment by leewaycn** [comment]
要是能做个类似的无缝切换高德地图和百度地图的类似mapview 就666了。
