### ISSUE TITLE
ios 12 奔溃在 uiwebview 初始化 怎么解决

### ISSUE THREAD

**Issue by yanlj** [li6185377/IMYWebView#24]
后台统计发现 ios12 有部分闪退 都是

WebCore | WebCore::FrameLoader::checkCompleted() + 592
-- | --
1 WebCore | WebCore::FrameLoader::init() + 740
2 WebCore | WebCore::FrameLoader::init() + 740
3 WebKitLegacy | +[WebFrame(WebInternal) _createMainFrameWithPage:frameName:frameView:] + 332
4 WebKitLegacy | -[WebView(WebPrivate) _commonInitializationWithFrameName:groupName:] + 2924
5 WebKitLegacy | -[WebView(WebPrivate) _initWithFrame:frameName:groupName:] + 132
6 UIKitCore | -[UIWebDocumentView initWithWebView:frame:] + 320
7 UIKitCore | -[UIWebBrowserView initWithWebView:frame:] + 48
8 UIKitCore | -[UIWebBrowserView initWithFrame:] + 44
9 UIKitCore | -[UIWebView _webViewCommonInitWithWebView:scalesPageToFit:] + 244
10 UIKitCore | -[UIWebView initWithFrame:] + 76
11 TfClient | -[IMYWebView initUIWebView] (IMYWebView.m:134)
12 TfClient | -[IMYWebView _initMyself] (IMYWebView.m:92)

知道是什么原因吗

**Comment by li6185377** [comment]
项目不咋维护了，苹果也要求用 WKWebView。。。
