### ISSUE TITLE
建议WKWebViewConfiguration初始化另起方法，方便子类能继承修改

### ISSUE THREAD

**Issue by 275080225** [li6185377/IMYWebView#25]
- (void)initWKWebView
 {
-    WKWebViewConfiguration* configuration = [[NSClassFromString(@"WKWebViewConfiguration") alloc] init];
-    configuration.userContentController = [NSClassFromString(@"WKUserContentController") new];
-    
-    WKPreferences* preferences = [NSClassFromString(@"WKPreferences") new];
-    preferences.javaScriptCanOpenWindowsAutomatically = YES;
-    configuration.preferences = preferences;
-    
-    WKWebView* webView = [[NSClassFromString(@"WKWebView") alloc] initWithFrame:self.bounds configuration:configuration];
+    WKWebView* webView = [[NSClassFromString(@"WKWebView") alloc] initWithFrame:self.bounds configuration:[self configuration]];
     webView.UIDelegate = self;
     webView.navigationDelegate = self;

- (WKWebViewConfiguration*)configuration
{
    WKWebViewConfiguration* configuration = [[NSClassFromString(@"WKWebViewConfiguration") alloc] init];
    configuration.userContentController = [NSClassFromString(@"WKUserContentController") new];
    
    WKPreferences* preferences = [NSClassFromString(@"WKPreferences") new];
    preferences.javaScriptCanOpenWindowsAutomatically = YES;
    configuration.preferences = preferences;
    return configuration;
}

**Comment by li6185377** [comment]
项目不咋维护了... 看下自己魔改下？
