### ISSUE TITLE
首次进来是uiwebview 再次进来就是wkwebview 了 这是不是个bug

### ISSUE THREAD

**Issue by shaveKevin** [li6185377/IMYWebView#3]
我们的程序目前兼容iOS7 想  iOS7用uiwebview  iOS8 用wkwebivew    。 你的这个demo 里第一次加载是webview吧  第二次 加载才用的是wkwebview  。 我们应用中有一个全是图片的html 高度 5w多。  测试手机6plus  测试结果 使用UIWebview 内存挂掉。 使用wkwebview
 内容加载不出来。 计算高度采用的是添加观察者。

**Comment by li6185377** [comment]
不是，判断有WKWebView 就会使用WKWebView的。 没有第一第二次

**Comment by li6185377** [comment]
在 tabbar 那边我会显示当前使用什么类

**Comment by shaveKevin** [comment]
我试过了 会使用UIWebview 来加载的  你看一下这个测试的demo  https://github.com/shaveKevin/Webview

**Comment by shaveKevin** [comment]
不知道是我使用的方式不对还是什么情况。。求解

**Comment by li6185377** [comment]
![image](https://cloud.githubusercontent.com/assets/1924211/14010255/79fa35cc-f1ce-11e5-9eb4-d025702fb4f0.png)
你如果不用poddao导入。 需要自己添加 WebKit

**Comment by shaveKevin** [comment]
got  it
