### ISSUE TITLE
IOS8之后WKWebVIew获取内部scrollView.contentSize为0.

### ISSUE THREAD

**Issue by linsaw** [li6185377/IMYWebView#6]
有个需求是算出web的高度，要再后面add一个UIView，IOS7的话，在- (void)webViewDidFinishLoad:(IMYWebView *)webView之后获取到的webView.scrollView.contentSize有值，IOS8之后获取到的为0.

**Comment by li6185377** [comment]
可以直接用KVO监听 loading， 结束后 去获取contentSize 。
